name: "Newman Tests"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: postman/newman

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Run API Tests
      - name: Run API Tests
        run:  newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json
